### PR TITLE
Add neutral button

### PR DESCRIPTION
**Pull request by JaviChaques**
- Add neutral button
- Update Build Tools Version to 25.0.3
- Update Support Library Version to 25.4.0

### CODE REVIEW

**Comment by J-Jamet** [comment]
Thank you, I look, I merge and I integrate in the new version. :)

**Comment by J-Jamet** [comment]
I'll reuse your technique of `def supportVersion` for my other projects, however there was a bug in the sample when changing the orientation and the dialog is open (listener does'nt work). And the listener was no longer compatible with the old notation. I changed that by adding `OnButtonWithNeutralClickListener` in the develop branch with new Readme. Can you tell me the advantage of having **\'** in place of **\"** in the build files and why you explicitly add `maven { url "https://maven.google.com" }` (I'm seriously thinking of changing the repo to put on maven but I'm not an expert and jitpack is easy). So thanks for the contribution and delete tests not used. :)

**Comment by JaviChaques** [comment]
Sorry I didn't try to change the orientation.
If you use " you can use variables into the string, for example "$supportVersion."

I add this maven because Google add the support library new versions to this repository.
[https://developer.android.com/topic/libraries/support-library/setup.html](https://developer.android.com/topic/libraries/support-library/setup.html)

**Comment by JaviChaques** [comment]
Can you distribute new version on Jitpack?

Thanks

**Comment by J-Jamet** [comment]
I have to incorporate some bug fixes before making another version. I'll try to do it quickly.

**Pull request merged**
